name: GAPTestPackage
version: "1.4.6"
license: "GPL-2.0-or-later"
date: 2025-11-28
description: |
    Library of finite groups with small class number

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.14"

www: https://stertooy.github.io/GAPTestPackage
readme: README.md
packageinfo: https://stertooy.github.io/GAPTestPackage/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/GAPTestPackage/releases/download/v1.4.6/GAPTestPackage-1.4.6.tar.gz

abstract: |
    Library of finite groups with small class number.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    conjugacy, conjugacy class, class number.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter25</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>GAPTestPackage, Library of finite groups with small class number,
             Version 1.4.6</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/GAPTestPackage">https://stertooy.github.io/GAPTestPackage</a></span>.
    </p>
    

bibtex: |
    @misc{ GAPTestPackage,
      author =           {Tertooy, S.},
      title =            {{GAPTestPackage}, {Library of finite groups with small
                          class number}, {V}ersion 1.4.6},
      month =            {Nov},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href      {https://stertooy.github.io/GAPTestPackage}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{GAPTestPackage}}},
      keywords =         {conjugacy; conjugacy class; class number},
      printedkey =       {Ter25}
    }

